

### GET status
# @name getStatus
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/room-status/ HTTP/1.1
# Content-Type: "application/json"

# {  
#   "target": "novalars@novalars.onmicrosoft.com",
#   "message":"This is the first message xxx" 
# }

### POST status
POST https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/room-status?token={{$dotenv TOKEN1}}&token2={{$dotenv TOKEN2}}&token3={{$dotenv TOKEN3}} HTTP/1.1
Content-Type: "application/json"

{
  "doorState": "open",
  "lockState": "close",
  "camPersonAlertState": "no",
  "camAnimalAlertState": "yes",
  "camMotionAlertState": "no",
  "smokeAlertState": "no",
  "roomTemp": "22.5"
}