name: 🚀 Deploy TEST Stage wp-plugin-room-status

on:
  push:
    branches:  
      - "feature/**"

jobs:
  web-deploy:
    name: 🎉 Deploy at https://spielwiese.erfindergeist.org/
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: erfindergeist.org
        username: ${{ secrets.FTP_USERNAME_TEST }}
        password: ${{ secrets.FTP_PASSWORD_TEST }}
        local-dir: ./
        protocol: ftps
        state-name: .ftp-deploy-test-stage-wp-plugin-room-status-state.json
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/test*
          **/test*/**
          **/homeAssistant*
          **/homeAssistant*/**